name: Artemis.Plugins.LayerBrushes.Image - Build and upload

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - 'src/Artemis.Plugins.LayerBrushes.Image/**'

jobs:
    upload:
        uses: ./.github/workflows/plugin-upload.yml
        with:
            projectPath: 'src/Artemis.Plugins.LayerBrushes.Image/Artemis.Plugins.LayerBrushes.Image.csproj'
        secrets:
            WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}